### PR TITLE
Fix #430 - check for --help flag before checking empty flags

### LINKED ISSUE #430: Help does not work
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Expected behaviour

`$ go run ./sysl2/sysl import --help`

Should give help on how to use the import command

### Actual behaviour

    ERRO[0000] 'output' value passed is empty
    'format' value passed is empty 
    exit status 1

### Steps to reproduce the behaviour

just try to run the help on any command

### PR DESCRIPTION
**Pull request by anz-gordonj7**
Fixes #430 

If the --help flag is provided on a specific command, but that command has any empty-by-default flags the woould error out instead of showing the help text, fix that.

@anz-bank/sysl-developers

### CODE REVIEW

File: sysl2/sysl/cmd_runner.go [hunk 1]
```diff
@@ -84,6 +84,13 @@ func EnsureFlagsNonEmpty(cmd *kingpin.CmdClause, excludes ...string) {
 	}
 	fn := func(c *kingpin.ParseContext) error {
 		var errorMsg strings.Builder
+		for _, elem := range c.Elements {
+			if f, _ := elem.Clause.(*kingpin.FlagClause); f != nil {
+				if f.Model().Name == "help" {
```
Comment (nofun97) [inline sysl2/sysl/cmd_runner.go]: nitpicky but what about
```go
if f, _ := elem.Clause(*kingpin.FlagClause); f != nil && f.Model.Name == "help"{
    return nil
}
```

Comment (nofun97) [reply sysl2/sysl/cmd_runner.go]: or is that too long?

Comment (anz-gordonj7) [reply sysl2/sysl/cmd_runner.go]: indeed, very nitpicky, but maybe slightly moore readable.
