### PR TITLE
Fix generated JsonDesererialzer Java code errors

### LINKED ISSUE #66: Uncompilable Java code generated for nested !type
### Expected behaviour
`reljam model` should create compilable code for nested types.

### Actual behaviour
Generated code does not compile

### Steps to reproduce the behaviour
```
> cat article.sysl
ArticleModel [version="0.0.1", package="io.sysl.bug"]: 
    !type Article: 
        content <: Content

    !type Content:
        Text <: string
> reljam --out gen model /article ArticleModel
> javac gen/io/sysl/bug/*.java
gen/io/sysl/issue66/ArticleModelJsonDeserializer.java:86: error: cannot find symbol
                case "content": entity.setContent(p.getCurrentToken() == JsonToken.VALUE_NULL ? null : deserialize(p, entity.getcontent()));  break;
                                                                                                                            ^
  symbol:   method getcontent()
  location: variable entity of type Article
1 error
```
[ internal: SYSL-35 ]

### PR DESCRIPTION
**Pull request by juliaogris**
Fixes #66.

Changes proposed in this pull request:
- Fix bad case in serializer.py
- Add a Java test

@anz-bank/sysl-developers

### CODE REVIEW

File: test/java/src/test/java/TestArticle.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+{
+    @Test
+    public void testJson() throws IOException {
+        Article a1 = buildArticle();
+        Article a2 = articleFromJson();
+        assertEquals(a1, a2);
+    }
+
+    public static Article articleFromJson() throws IOException {
+		JsonFactory factory = new JsonFactory();
```
Comment (camh-anz) [inline test/java/src/test/java/TestArticle.java]: The indenting has gone funny in thus method - tabs vs spaces?

File: test/java/src/test/java/TestArticle.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    	String s = "{\"content\" : { \"Text\" : \"Peace and love\" } }";
+		JsonParser  p  = factory.createParser(s);
```
Comment (camh-anz) [inline test/java/src/test/java/TestArticle.java]: nit: there's a double space before the =

**Comment by camh-anz** [comment]
So I was wrong about the PR not referencing the the issue - there it is right up front. I guess I missed it because I go straight to the commits. I'll pay more attention next time.

File: test/java/src/test/java/TestArticle.java (hunk 1 above)
Comment (juliaogris) [reply test/java/src/test/java/TestArticle.java]: Done, thanks. I run into this quite regularly - I think it's when I copypasta from somewhere else. Do you have a tool that you run to avoid such issues or should I just see if I can change something in my editor?

File: test/java/src/test/java/TestArticle.java (hunk 2 above)
Comment (juliaogris) [reply test/java/src/test/java/TestArticle.java]: Done
