### PR TITLE
Fix modules path when root marker exists

### LINKED ISSUE #519: sysl-modules: module's path is wrong when root marker exists
The path of `go get <module-path>` is wrong when the root marker exists.

### Expected behaviour
no errors

### Actual behaviour
Output error: `error parsing <wrong-path>: <wrong-path> not found`

### Steps to reproduce the behaviour
1. `mkdir .sysl` under the sysl repo path
2. `sysl validate -v ./demo/examples/Modules/model_with_deps.sysl`
=> ERRO[0000] error parsing "demo/examples/Modules/github.com/anz-bank/sysl/tests/bananatree.sysl": demo/examples/Modules/github.com/anz-bank/sysl/tests/bananatree.sysl not found

### PR DESCRIPTION
**Pull request by ChloePlanet**
Fixes #519  .

Changes proposed in this pull request:
- Wrap project filesystem up in mod.Fs while configure project instead of cmdRunner.Run
- Use `//...` to represent non-local imports. i.e. `import //github.com/org/repo/deps`, `import //github.com/anz-bank/sysl/tests/deps`

@anz-bank/sysl-developers

### CODE REVIEW

File: cmd/sysl/sysl.go [hunk 1]
```diff
@@ -107,7 +108,12 @@ func (pc *projectConfiguration) configureProject(root, module string, fs afero.F
 		}
 	}
 
-	pc.fs = syslutil.NewChrootFs(fs, pc.root)
+	var projfs afero.Fs = syslutil.NewChrootFs(fs, pc.root)
+	if mod.SyslModules {
+		projfs = mod.NewFs(projfs)
+	}
+	pc.fs = projfs
```
Comment (anzdaddy) [inline cmd/sysl/sysl.go]: nit: You can assign straight into `pc.fs` instead of using a tempvar.

File: pkg/mod/module_test.go [hunk 2]
```diff
@@ -43,7 +43,8 @@ func TestGetByFilepathWithNilMods(t *testing.T) {
 func TestFind(t *testing.T) {
 	t.Parallel()
 
-	filename := "github.com/anz-bank/sysl/demo/examples/Modules/deps.sysl"
+	SyslModules = "on"
```
Comment (golangcibot) [inline pkg/mod/module_test.go]: cannot convert "on" (untyped string constant) to bool (from `typecheck`)

**Comment by anzdaddy** [comment]
LGTM
