### PR TITLE
Fix issue #232 and #233

### LINKED ISSUE #232: go sysl sd produces empty png file.
### Steps to reproduce the behaviour
cd to  repo, `sysl/docs/assets` directory:

Python sysl sd command produces the correct output:
`sysl sd -s 'MobileApp <- Login' -o call.png call`

But the equivalent go-sysl-sd command:

`sd -endpoint 'MobileApp <- Login' -output call.png -modules call.sysl`

produces an empty file `call.png`.

### Expected behaviour
The above mentioned command should generate the correct sequence diagram

Another issue:
The python and go versions do not have the same command line options.

### PR DESCRIPTION
**Pull request by loki5265**
* Add default value for SYSL_PLANTUML
* Add kingpin package to handle command-line args
* Align command-line args with python

Fixes #232, #233 .

Changes proposed in this pull request:
-
-

@anz-bank/sysl-developers

### CODE REVIEW

File: sysl2/sysl/seqs.go [hunk 1]
```diff
@@ -147,34 +135,36 @@ func DoGenerateSequenceDiagrams(stdout, stderr io.Writer, flags *flag.FlagSet, a
...
-	endpoint_format := flags.String("endpoint_format", "%(epname)", "Specify the format string for sequence diagram endpoints. "+
-		"May include %%(epname), %%(eplongname) and %%(@foo) for attribute foo(default: %(epname))")
-	app_format := flags.String("app_format", "%(appname)", "Specify the format string for sequence diagram participants. "+
-		"May include %%(appname) and %%(@foo) for attribute foo(default: %(appname))")
-	title := flags.String("title", "", "diagram title")
-	plantuml := flags.String("plantuml", "", strings.Join([]string{"base url of plantuml server",
+	sd := kingpin.New("sd", "Generate sequence diagram")
+	root := sd.Flag("root", "sysl root directory for input model file (default: .)").Default(".").String()
+	endpoint_format := sd.Flag("endpoint_format", "Specify the format string for sequence diagram endpoints. "+
+		"May include %%(epname), %%(eplongname) and %%(@foo) for attribute foo(default: %(epname))").Default("%(epname)").String()
```
Comment (sahejsingh) [inline sysl2/sysl/seqs.go]: %%(epname) is incorrect.
Only need 1 `%` character.

File: sysl2/sysl/seqs.go [hunk 2]
```diff
@@ -147,34 +135,36 @@ func DoGenerateSequenceDiagrams(stdout, stderr io.Writer, flags *flag.FlagSet, a
...
+	app_format := sd.Flag("app_format", "Specify the format string for sequence diagram participants. "+
+		"May include %%(appname) and %%(@foo) for attribute foo(default: %(appname))").Default("%(appname)").String()
+	title := sd.Flag("title", "diagram title").Short('t').String()
+	plantuml := sd.Flag("plantuml", strings.Join([]string{"base url of plantuml server",
```
Comment (sahejsingh) [inline sysl2/sysl/seqs.go]: is it possible to set the default value of plantuml here?

File: sysl2/sysl/seqs/diagutil.go [hunk 3]
```diff
@@ -20,6 +20,10 @@ func OutputPlantuml(output, plantuml, umlInput string) {
 		plantuml = os.Getenv("SYSL_PLANTUML")
 	}
 
+	if plantuml == "" {
```
Comment (sahejsingh) [inline sysl2/sysl/seqs/diagutil.go]: Remove this and set default where you add the plantuml command line arg.

File: sysl2/sysl/seqs.go [hunk 4]
```diff
@@ -147,34 +135,36 @@ func DoGenerateSequenceDiagrams(stdout, stderr io.Writer, flags *flag.FlagSet, a
...
+		"comma-list of shell globs) to limit the diagrams generated").Short('a').Strings()
+	blackboxes_flag := sd.Flag("blackbox", "Apps to be treated as black boxes").Strings()
 
 	// Following variables currently are unused. Keep them to align with the python version.
-	filter := flags.String("filter", "", "Only generate diagrams whose output paths match a pattern")
-	no_activations := flags.Bool("no-activations", true, "Suppress sequence diagram activation bars(default: true)")
-	verbose := flags.Bool("verbose", false, "Report each output(default: false)")
-	expire_cache := flags.Bool("expire-cache", false, "Expire cache entries to force checking against real destination(default: false)")
-	dry_run := flags.Bool("dry-run", false, "Don't perform confluence uploads, but show what would have happened(default: false)")
+	filter := sd.Flag("filter", "Only generate diagrams whose output paths match a pattern").String()
```
Comment (sahejsingh) [inline sysl2/sysl/seqs.go]: remove these if we are not handling them.

File: sysl2/sysl/seqs.go [hunk 5]
```diff
@@ -184,7 +174,7 @@ func DoGenerateSequenceDiagrams(stdout, stderr io.Writer, flags *flag.FlagSet, a
 	log.Debugf("no_activations: %t\n", *no_activations)
 	log.Debugf("endpoint_format: %s\n", *endpoint_format)
 	log.Debugf("app_format: %s\n", *app_format)
-	log.Debugf("blackbox: %s\n", blackboxes_flag)
+	log.Debugf("blackbox: %s\n", *blackboxes_flag)
```
Comment (sahejsingh) [inline sysl2/sysl/seqs.go]: how do i run at debug level? there should be an option to change the log level.

File: sysl2/sysl/seqs.go (hunk 1 above)
Comment (loki5265) [reply sysl2/sysl/seqs.go]: Firstly I copy this description from python and I thought it's correct.
Delete 1 %.

File: sysl2/sysl/seqs.go (hunk 2 above)
Comment (loki5265) [reply sysl2/sysl/seqs.go]: It's possible. But I get another question. After setting default value here, I believe part of the code in diagutil.go should be changed too.
if plantuml == "" {
	plantuml = os.Getenv("SYSL_PLANTUML")
} If better to remove this, too?

File: sysl2/sysl/seqs/diagutil.go (hunk 3 above)
Comment (loki5265) [reply sysl2/sysl/seqs/diagutil.go]: yep, remove it.

File: sysl2/sysl/seqs.go (hunk 4 above)
Comment (loki5265) [reply sysl2/sysl/seqs.go]: removed.

File: sysl2/sysl/seqs.go (hunk 5 above)
Comment (loki5265) [reply sysl2/sysl/seqs.go]: add "log" command line arg to handle this.

File: test-gosysl.sh [hunk 6]
```diff
@@ -8,3 +8,10 @@ for f in $ROOT/*.sysl; do
 done;
 
 rm $ROOT/*.out.txt
+
+ln -s $GOPATH/bin/sysl $GOPATH/bin/sd
+$GOPATH/bin/sd -a 'Project' $ROOT/sequence_diagram_project.sysl
+rm _.png
```
Comment (sahejsingh) [inline test-gosysl.sh]: How do you know if the file is getting generated here?
there is no server running on localhost:8080.
and the code here https://github.com/anz-bank/sysl/blob/master/sysl2/sysl/seqs/diagutil.go#L19 does not use value of SYSL_PLANTUML because plantuml has a default value. right?

Comment (loki5265) [reply test-gosysl.sh]: I revert the logic to check the SYSL_PLANTUML. If no value from command arg, will use the value from SYSL_PLANTUML. If env not setted, will use default value of "http://localhost:8080/plantuml".
And actually I'm not sure how to run the binary test. I add a new arg value for plantuml with "http://www.plantuml.com/plantuml". Hope it work.

File: sysl2/sysl/seqs/diagutil.go (hunk 3 above)
Comment (sahejsingh) [reply sysl2/sysl/seqs/diagutil.go]: all the checks on `plantuml` should move to where the command line args are evaluated. Not here.
One place where it could be is to move lines 19-24 to seqs.go

File: test-gosysl.sh (hunk 6 above)
Comment (loki5265) [reply test-gosysl.sh]: yep. I've removed the -p param from the go-testsysl.sh file.

File: sysl2/sysl/seqs.go [hunk 7]
```diff
@@ -147,55 +136,59 @@ func DoGenerateSequenceDiagrams(stdout, stderr io.Writer, flags *flag.FlagSet, a
...
+		log.SetLevel(level)
+	}
+
+	if *plantuml == "" {
+		*plantuml = os.Getenv("SYSL_PLANTUML")
+	}
+	if *plantuml == "" {
+		*plantuml = "http://localhost:8080/plantuml"
+	}
+
```
Comment (sahejsingh) [inline sysl2/sysl/seqs.go]: small nit pick:
if you pass plantuml in the cmd line
then you are checking the value of plantuml twice.

Comment (sahejsingh) [reply sysl2/sysl/seqs.go]:
```
if *plantuml == "" {
        if *plantuml, has = os.LookupEnv("SYSL_PLANTUML"); !has {
            *plantuml = "http://localhost:8080/plantuml"
        }
    }
```
