### PR TITLE
Ints fix

### LINKED ISSUE #260: go-sysl ints does not draw indirect arrows between apps
gosysl and pysysl have the following difference:
```
IntegratedSystem:
    integrated_endpoint_1:
        Systema <- endpoint

    integrated_endpoint_2:
        System_b <- endpoint

Systema:
    endpoint:
        System_b <- endpoint

Project [appfmt="%(appname)", epfmt="%(epname)", indirect_arrow_color="silver"]:

    indirect_arrow:
        IntegratedSystem

System_b:
    endpoint: ...
    endpoint2:
      System_c <- endpoint2

System_c:
    endpoint: ...
    endpoint2: ...
```
### Expected behaviour
indirect_arrow

### Actual behaviour
indirect_arrow

### Steps to reproduce the behaviour
Command:
go command
`ints  -o '%(epname).png' -j Project b.sysl`
py command
`sysl ints  -o '%(epname).png' -j Project b.sysl`

### PR DESCRIPTION
**Pull request by sahejsingh**
Fixes #260 

Changes proposed in this pull request:
- stable output that can be compared across runs
- handles: passthrough, excludes, indirect arrows, callers to the `integrations` set

@anz-bank/sysl-developers

### CODE REVIEW

File: sysl2/sysl/ints_builder.go [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+	b.seedAppsMap = MakeStrSet(b.seedApps...)
+	// add direct dependencies of seedApps
+	// dont include targetApp if its in exclude
+	// if targetApp in passthrough, only add apps that are called by this endpoint
+	// and do this recursively till the app is in passthrough
+	for _, appname := range b.seedApps {
+		// fmt.Println(appname)
+		app := apps[appname]
+		for _, epname := range sortedSlice(app.GetEndpoints()) {
+			if epname != ".. * <- *" {
```
Comment (golangcibot) [inline sysl2/sysl/ints_builder.go]: string `.. * <- *` has 3 occurrences, make it a constant (from `goconst`)

File: sysl2/sysl/ints_test.go [hunk 2]
```diff
@@ -86,54 +21,39 @@ type intsArg struct {
...
-		rootModel: "./tests/",
-		modules:   "integration_test.sysl",
-		output:    "%(epname).png",
-		project:   "Project",
+func comparePUML(t *testing.T, expected, actual map[string]string) {
+	for name, goldenFile := range expected {
+		golden, err := ioutil.ReadFile(goldenFile)
+		assert.Nil(t, err)
+		if string(golden) != actual[name] {
+			ioutil.WriteFile("tests/"+name+".puml", []byte(actual[name]), 0777)
```
Comment (golangcibot) [inline sysl2/sysl/ints_test.go]: Error return value of `ioutil.WriteFile` is not checked (from `errcheck`)
