### PR TITLE
Union fixing

### LINKED ISSUE #976: Syntax union issue
### Description
As https://sysl.io/docs/lang-spec/#union `!union string, int32` should work, but it can't actually.

### Steps to Reproduce
1. Created Sysl file demo.sysl
```
Project:
    App:
        Simple

Simple:
    !type User:
        id <: string
        ping <: StringOrInt32

    !union StringOrInt32:
        a
        b
    
    !alias a:
        string

    !alias b:
        int32

    !union string, int32
```
2. Run command `sysl datamodel -j Project -d demo.sysl`
### Expected behavior
It can run successfully and output diagram

### Actual behavior
It is crashed and output error:
```
$ sysl datamodel -j Project -d demo.sysl
line 20:11 mismatched input 'string' expecting {TEXT_LINE, Name, E_Name}
ERRO[0000] demo.sysl has syntax errors      
```
It can't pass Sysl syntax parsing.

And the alternative option is:
```
!union StringOrInt32:
        a
        b

!alias a:
        string
!alias b:
        int32
```

### Your Environment
```sh
$ sysl info
Build:
  Version         :  v0.155.0
  Git Commit   : 7f4486576e79474836ac6e8377458aab7239dd9e
  Date              : 2020-07-29T08:14:51Z
  Go Version   : go1.14 darwin/amd64
  OS                 : darwin/amd64
```

### PR DESCRIPTION
**Pull request by ericzhang6222**
* Please attach **WIP** tag when this PR is still work in progress.
* Please attach **breaking-change** tag if this PR potentially causes other components to fail or changes previous sysl executable's behaviour.

Fixes #976 .

Changes proposed in this pull request:
- It can support following syntax:
```
Test:
    !type A: ...
    !type B: ...
    !type C: ...

    !union U:
        A
        B
        C

    !union Mixed:
        int
        string
        sequence of string
        set of bytes
        A
        U
``` 

Checklist:
- [x] Added related tests
- [x] Made corresponding changes to the documentation

### CODE REVIEW

File: pkg/parse/listener_impl.go [hunk 1]
```diff
@@ -802,31 +805,33 @@ func (s *TreeShapeListener) EnterUnion(ctx *parser.UnionContext) {
 	type1.SourceContext = s.sc.Get(ctx.BaseParserRuleContext)
 }
 
+// EnterUnion_type is called when production union_type is entered.
+func (s *TreeShapeListener) EnterUnion_type(ctx *parser.Union_typeContext) {
+	fieldName := ctx.GetText()
+	s.fieldname = append(s.fieldname, fieldName)
+	dataType, has := s.typemap[fieldName]
+	if has {
+		logrus.Warnf("%s) %s.(%s) defined multiple times, merge definitions",
```
Comment (andrewemeryanz) [inline pkg/parse/listener_impl.go:814]: This error could be confused to mean that the definitions are merged. I think it actually means that the second definition is ignored. Perhaps something like `%s) %s.(%s) defined multiple times, redefinition ignored` would be better.

**Review by andrewemeryanz — APPROVED** [review]
