### PR TITLE
json serializer fixes

### LINKED ISSUE #32: Generated JSON serializer does not work for tuple based models
### Expected behaviour
Define !type based model
use reljam to generate java code
try to compile the generated java code.

### Actual behaviour

- Incomplete/Incorrect java code is generated that does not compile.

### Steps to reproduce the behaviour

e.g. model
`> cat tuplecomplex.sysl`

```
UserFormComplex [package="com.test.example.tuple.complex"]:
    !type BuyItemFormComplex:
        FirstName <: string
        LastName <: string
        BillingAddress <: Address
        CustomerType <: CustomerType
        Amount <: decimal(10,2)
        Emails <: set of Email
        DateOfBirth <: Date

    !type Address:
        Address1 <: string
        Address2 <: string
        City <: string
        State <: string
        ZipCode <: string
        Country <: string

    !type Email:
        Email <: string

    !enum CustomerType:
        INDIVIDUAL = 0
        BUSINESS = 1
```

`> reljam --out 'src/main/java' model /tuplecomplex UserFormComplex`

compile the generated java code.

### PR DESCRIPTION
**Pull request by sahejsingh**
Fixes #32 
Changes proposed in this pull request:
- Implements JSON serializer and deserialzer for Tuple based model
This change adds the required methods in the generated Java Serialiser code.
The unit test shows how to use the generated java code to serializer and deserialize the model. 

@anz-bank/sysl-developers

### CODE REVIEW

File: java/io/sysl/Enumerable.java [hunk 1]
```diff
@@ -0,0 +1,206 @@
+package io.sysl;
```
Comment (juliaogris) [inline java/io/sysl/Enumerable.java]: I blieve all `java/io/sysl/*` files are already present in `src/libs/java/io/sysl/*` please use that location.

File: .travis.yml [hunk 2]
```diff
@@ -8,6 +10,8 @@ env:
   - SYSL_PLANTUML=http://www.plantuml.com/plantuml
 install:
   - pip install . pytest flake8
+  - pip install --upgrade six
```
[the remark this answers is not in the document]
Comment (juliaogris) [reply .travis.yml]: Both lines above

[the remark this answers is not in the document]
Comment (sahejsingh) [reply .travis.yml]: i only added the "upgrade six" line because the travis docker image i was using had older version of six which generated an error when I tried to generate java code using reljam.

Not sure what you mean by "both lines". Anyway looks like the travis-ci does not have that issue.

File: .travis.yml [hunk 3]
```diff
@@ -8,6 +10,8 @@ env:
...
 script:
   - flake8
   - pytest
+  - cd test/java && /usr/local/gradle/bin/gradle build
```
[the remark this answers is not in the document]
Comment (sahejsingh) [reply .travis.yml]: for some reason I didnt get any output when i tried 'which gradle' on the travis local docker image.
That is why I ended up referring to the absolute path. Funny enough, the local image now shows the correct output for 'which gradle'

File: java/io/sysl/Enumerable.java (hunk 1 above)
Comment (sahejsingh) [reply java/io/sysl/Enumerable.java]: the internal repo had that at root. Didnt realize this code had moved to a new location.

File: java/io/sysl/Enumerable.java [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+    }
+
+    public <U> U reduce(U u, Reducer<T, U> reducer) {
+        for (T t : this) {
+            u = reducer.reduce(u, t);
+        }
+        return u;
+    }
+
+    // public <U> U reduce(Reducer<T, U> reducer) {
```
[the remark this answers is not in the document]
Comment (sahejsingh) [reply java/io/sysl/Enumerable.java]: All the java/io/* files have been deleted.

File: test/java/build.gradle [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+        url "http://repo1.maven.org/maven2"
+    }
+    jcenter {
+        url "http://jcenter.bintray.com/"
+    }
+}
+
+task generateSysl(type:Exec) { 
+   //on linux'
+  commandLine 'python', '-m', 'sysl.reljam',  '--out', 'src/main/java', 'model', '/tuplecomplex', 'UserFormComplex'
```
[the remark this answers is not in the document]
Comment (sahejsingh) [reply test/java/build.gradle]: I added this because gradle could not find 'reljam' after doing 'pip install' in my local travis docker image. Not sure why. 
Anyway, things are working now.

File: .gitignore [hunk 6]
```diff
@@ -6,3 +6,4 @@ build
 .eggs
 
 /test/e2e/actual_output
+test/java/src/main/java/com/test
```
Comment (juliaogris) [inline .gitignore]: Please move the test output to output to `<repo>/tmp`.
On my system for a clean repo `.gradle` is also required here see:
https://github.com/juliaogris/sysl/blob/json_serializer_mv/.gitignore

File: .travis.yml [hunk 7]
```diff
@@ -11,3 +11,4 @@ install:
 script:
   - flake8
   - pytest
+  - cd test/java && gradle build
```
[the remark this answers is not in the document]
Comment (juliaogris) [reply .travis.yml]: See https://github.com/juliaogris/sysl/blob/json_serializer_mv/.travis.yml and working build at https://travis-ci.org/juliaogris/sysl/builds/328917700

File: test/java/build.gradle [hunk 8]
```diff
@@ -0,0 +1,44 @@
+apply plugin: 'java-library'
```
Comment (juliaogris) [inline test/java/build.gradle]: Keep quotation marks consistent - apprently `"` is the way to go.
See update at: 
https://github.com/juliaogris/sysl/blob/json_serializer_mv/test/java/build.gradle

File: test/java/build.gradle [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+
+repositories {
+    mavenLocal()
+    jcenter()
+}
+
+task generateSysl(type:Exec) {
+  commandLine 'reljam',  '--out', 'src/main/java', 'model', '/tuplecomplex', 'UserFormComplex'
```
Comment (juliaogris) [inline test/java/build.gradle]: Move output to `"../../tmp/test/java"`

File: test/java/build.gradle [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+
+compileJava.dependsOn generateSysl
+
+sourceSets {
+    main {
+        java {
+            srcDirs = ["src/main/java", "../../src/libs/java"]
+        }
+        resources {
+            srcDir 'src/main/resources'
```
Comment (juliaogris) [inline test/java/build.gradle]: Move resources to top level please and change this line to:
`srcDir "resources"`

File: test/java/build.gradle [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+        }
+    }
+
+    test {
+        java {
+            srcDirs = ["src/test/java"]
```
Comment (juliaogris) [inline test/java/build.gradle]: move to `srcDirs = ["src"]`

File: test/java/build.gradle [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+        }
+    }
+}
+
+
+dependencies {
+    api "joda-time:joda-time:2.5"
+    api "org.apache.commons:commons-lang3:3.5"
+    implementation "com.fasterxml.jackson.datatype:jackson-datatype-joda:2.6.3"
+
```
Comment (juliaogris) [inline test/java/build.gradle]: unnecessary blank line

File: test/java/src/main/resources/test.json [hunk 13]
```diff
@@ -0,0 +1,14 @@
+{
```
Comment (juliaogris) [inline test/java/src/main/resources/test.json]: please rename to `test_1.json` for consistency (https://github.com/juliaogris/sysl/tree/json_serializer_mv/test/java/resources)

File: test/java/src/test/java/TestJsonSerializer.java [hunk 14]
```diff
@@ -0,0 +1,120 @@
+import java.io.IOException;
```
Comment (juliaogris) [inline test/java/src/test/java/TestJsonSerializer.java]: I've got quite a few suggested changes for this file.
Please have a look here:
https://github.com/juliaogris/sysl/blob/json_serializer_mv/test/java/src/io/sysl/reljam/test/tuple/TestJsonSerializer.java

This also contains the `BigDecimal` fix, object comparison and simplified Exception handling

File: test/java/src/test/java/TestJsonSerializer.java [hunk 15]
```diff
@@ -0,0 +1,120 @@
...
+import java.io.File;
+
+import java.nio.file.Files;
+import java.nio.file.Paths;
+import java.util.HashSet;
+
+import com.fasterxml.jackson.core.*;
+import com.fasterxml.jackson.databind.ObjectMapper;
+import com.fasterxml.jackson.databind.module.SimpleModule;
+import com.test.example.tuple.complex.BuyItemFormComplex;
```
Comment (juliaogris) [inline test/java/src/test/java/TestJsonSerializer.java]: Rename package `com.test.example.tuple.complex` to `io.sysl.reljam.gen.tuple` or similar as we own the `sysl.io` domain.

Block first party, third-party and local imports - ie move all `io.sysl.reljam.gen.tuple` imports to the bottom.

File: test/java/src/test/java/TestJsonSerializer.java [hunk 16]
```diff
@@ -0,0 +1,120 @@
...
+        Email.Set emailSet = new Email.Set();
+        emailSet.add(one);
+        emailSet.add(two);
+
+        HashSet<String> s = new HashSet<String>();
+        s.add("one");
+        s.add("two");
+
+        BuyItemFormComplex e = new BuyItemFormComplex();
+        e.setAmount(new BigDecimal(10.11))
```
Comment (juliaogris) [inline test/java/src/test/java/TestJsonSerializer.java]: e.setAmount(new BigDecimal("10.11"))

File: test/java/tuplecomplex.sysl [hunk 17]
```diff
@@ -0,0 +1,36 @@
+UserFormComplex [package="com.test.example.tuple.complex"]:
```
Comment (juliaogris) [inline test/java/tuplecomplex.sysl]: Please use `io.sysl.reljam.gen.tuple` or similar package (see https://github.com/juliaogris/sysl/blob/json_serializer_mv/test/java/tuplecomplex.sysl)

File: src/sysl/exporters/json_out/serializer.py [hunk 18]
```diff
@@ -88,75 +88,155 @@ def serializer(context):
...
+                    with java.For(w, '{} item : view', tname):
+                        w('g.writeStartObject();')
+                        for (fname, f) in datamodel.sorted_fields(t):
+                            jfname = java.name(fname)
+                            method = java.CamelCase(jfname)
+                            type_ = datamodel.typeref(f, module)[2]
+                            extra = '{}'
+                            which_type = type_.WhichOneof('type')
+                            if which_type == 'primitive':
+                                (jsontype,
```
Comment (juliaogris) [inline src/sysl/exporters/json_out/serializer.py]: There are no parenthesis required around an expression list i.e. `jsontype, extra = ...` is enough.
There are a few instances of this in this change - please remove parenthesis in all occurrences and also in `for` statements e.g.`for x, y in xy_list:` rather than `for (x, y) in xy_list:.

File: src/sysl/exporters/json_out/serializer.py [hunk 19]
```diff
@@ -88,75 +88,155 @@ def serializer(context):
...
             w()
-            with java.Method(w, 'private', 'void', 'writeField'.format(t),
+            with java.Method(w, 'private', 'void', 'writeField',
                              [('JsonGenerator', 'g'),
                               ('String', 'fieldname'), (t, 'value')],
                              throws=['IOException']):
                 with java.If(w, 'value != null'):
                     w('g.write{}Field(fieldname, value);', t)
 
+        # TODO: implement for ['Boolean', 'Integer', 'Double', 'BigDecimal', 'DateTime', 'LocalDate', 'UUID']
```
Comment (juliaogris) [inline src/sysl/exporters/json_out/serializer.py]: TODO(sahejsingh):

File: src/sysl/exporters/json_out/serializer.py [hunk 20]
```diff
@@ -235,30 +315,116 @@ def deserializer(context):
...
+            w('expectToken(p, JsonToken.END_OBJECT);')
+            w()
+            if facade:
+                w('return facade;')
+            else:
                 w('return model;')
 
         for (tname, t) in sorted(app.types.iteritems()):
             if not t.HasField('relation'):
+                if t.HasField('tuple'):
```
Comment (juliaogris) [inline src/sysl/exporters/json_out/serializer.py]: Can you pull the last two lines together to avoid one indentation level as
`if not t.HasField('relation') and t.HasField('tuple'):` ?

File: src/sysl/exporters/json_out/serializer.py [hunk 21]
```diff
@@ -88,75 +88,155 @@ def serializer(context):
...
-            with java.Method(w, 'public', 'void', 'serialize' + tname + 'View',
-                             [('JsonGenerator', 'g'),
-                              (tname + '.View', 'view')],
-                             throws=['IOException']):
-                with java.If(w, 'view.isEmpty()'):
-                    w('return;')
-                w('g.writeArrayFieldStart("{}");', tname)
-                with java.For(w, '{} item : view', tname):
-                    w('g.writeStartObject();')
+            java.SeparatorComment(w)
```
Comment (juliaogris) [inline src/sysl/exporters/json_out/serializer.py]: This is a pretty big and complex change and very tricky to understand for me (even before these changes this was challenging code).
Could you please at least break up the `serializer` and `deserializer` functions into smaller junks if possible so that they become less than 200 line functions?
For details of this change I'll have to rely on @anzdaddy

File: src/sysl/exporters/json_out/serializer.py [hunk 22]
```diff
@@ -88,75 +88,155 @@ def serializer(context):
...
+                                 [('JsonGenerator', 'g'),
+                                  (tname, 'entity')],
+                                 throws=['IOException']):
+                    w(u'g.writeStartObject();')
                     for (fname, f) in datamodel.sorted_fields(t):
                         jfname = java.name(fname)
                         method = java.CamelCase(jfname)
                         type_ = datamodel.typeref(f, module)[2]
+                        which_type = ''
+                        if type_ is None:
```
Comment (juliaogris) [inline src/sysl/exporters/json_out/serializer.py]: `if not type_:` is more Pythonic and probably still correct here?

File: src/sysl/exporters/json_out/serializer.py (hunk 18 above)
Comment (sahejsingh) [reply src/sysl/exporters/json_out/serializer.py]: i think (x,y) is better.

File: test/java/build.gradle (hunk 10 above)
Comment (sahejsingh) [reply test/java/build.gradle]: I thought src/main/{java,resources} was the standard java structure.
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

File: test/java/src/main/resources/test_2.json [hunk 23]
```diff
@@ -0,0 +1,18 @@
...
+        "ZipCode": "3000",
+        "Country": "AU"
+    },
+    "CustomerType": 0,
+    "Amount": 10.11,
+    "Emails": [
+        { "Email": "john.smith@anz.com"},
+        { "Email": "jsmith@anz.com"}
+    ]
+}
```
[the remark this answers is not in the document]
Comment (sahejsingh) [reply test/java/src/main/resources/test_2.json]: the file that I pushed has an extra line. not sure why we are not seeing that extra line.

File: .gitignore [hunk 24]
```diff
@@ -6,3 +6,5 @@ build
 .eggs
 
 /test/e2e/actual_output
+test/java/.gradle/
```
Comment (juliaogris) [inline .gitignore]: please change to `.gradle` and move to other relatives paths under `.eggs`

File: .gitignore [hunk 25]
```diff
@@ -6,3 +6,5 @@ build
...
+tmp/
```
Comment (juliaogris) [inline .gitignore]: change to `/tmp`
Absolute paths in `.gitignore` need to start with leading `/`

File: src/sysl/exporters/xml/serializer.py [hunk 26]
```diff
@@ -298,6 +298,8 @@ def deserializer(context):
             w('expect(XMLStreamConstants.END_ELEMENT, xsr.getEventType());')
 
         for (tname, ft, t) in syslx.sorted_types(context):
+            if not t.HasField('relation'):
+                continue
```
Comment (juliaogris) [inline src/sysl/exporters/xml/serializer.py]: Nice!

File: test/java/build.gradle (hunk 8 above)
Comment (juliaogris) [reply test/java/build.gradle]: This is still missing.

File: test/java/build.gradle (hunk 11 above)
Comment (juliaogris) [reply test/java/build.gradle]: This is still not done.

File: test/java/src/test/java/TestJsonSerializer.java [hunk 27]
```diff
@@ -0,0 +1,104 @@
+import static org.junit.Assert.*;
+
+import java.io.File;
+import java.io.IOException;
+import java.io.StringWriter;
```
Comment (juliaogris) [inline test/java/src/test/java/TestJsonSerializer.java]: Please move this file to `test/java/src/io/sysl/reljam/test/tuple/`

File: test/java/src/test/java/TestJsonSerializer.java [hunk 28]
```diff
@@ -0,0 +1,104 @@
...
+        StringWriter w = new StringWriter();
+        JsonGenerator generator = factory.createGenerator(w);
+        generator.useDefaultPrettyPrinter();
+        UserFormComplexJsonSerializer ser = new UserFormComplexJsonSerializer();
+        ser.serialize(generator, entity);
+        generator.close();
+        return w.toString();
+    }
+
+    public static BuyItemFormComplex createBuyItemFormComplex() {
```
Comment (juliaogris) [inline test/java/src/test/java/TestJsonSerializer.java]: Please rename to `createBuyItemFormComplex1` as it corresponds to `test_1.json`

File: test/java/src/test/java/TestJsonSerializer.java [hunk 29]
```diff
@@ -0,0 +1,104 @@
...
+        String s1 = serialize(e1);
+        String s2 = serialize(e2);
+        assertEquals(s1, s2);
+    }
+
+    @Test
+    public void testSubObject()  throws IOException {
+        BuyItemFormComplex entity = loadBuyItemFormComplex("src/main/resources/test_2.json");
+        String str = serialize(entity);
+        assertTrue(str.equals(WITH_SUB_OBJECT));
```
Comment (juliaogris) [inline test/java/src/test/java/TestJsonSerializer.java]: If you insist on the string comparison - please explain the benefits (whitespace makes this more brittle) and rename `WITH_SUB_OBJECT` to `TEST2_JSON`.

File: src/sysl/exporters/json_out/serializer.py (hunk 21 above)
Comment (juliaogris) [reply src/sysl/exporters/json_out/serializer.py]: Have you had a look @anzdaddy?

File: test/java/build.gradle (hunk 10 above)
Comment (juliaogris) [reply test/java/build.gradle]: Hm, but it's `tests` we have got here not `main` code, so it should at least be `src/test/{java,resources} `
It seems like the right way at the `repo_root` but 
`tests/java/src/java` or `tests/java/test/java` reads strange.
On that note, the right solution might be to put the `build.gradle` file in the `repo_root` directory.
This would also make the CI call cleaner:
`gradle test` rather than `cd tests/java && gradle test`

File: src/sysl/exporters/json_out/serializer.py (hunk 18 above)
Comment (juliaogris) [reply src/sysl/exporters/json_out/serializer.py]: Ok, this seems to be an opinion issue. 
I've tried hard to find a reference with authority that tuple unpacking e.g. `a, b = b, a` is more pythonic than with parens but I couldn't, so let's drop this.

Comment (anzdaddy) [reply src/sysl/exporters/json_out/serializer.py]: I prefer consistently including the parens because it's always clear and unambiguous, whereas it isn't always obvious when parens may be safely omitted, e.g.: `[a, b for b, a in range(5)]`, and `world[x, y]` vs `world[x,y:z]`. I also don't like the inconsistency of having a different rule for the outer node of a deep structure: `for i, (x, y) in enumerate(points):`

(I am of course at odds with most Python programmers, who favour omitting them whenever possible.)

File: src/sysl/exporters/json_out/serializer.py (hunk 21 above)
Comment (anzdaddy) [reply src/sysl/exporters/json_out/serializer.py]: No, and I probably won't have a chance to do so till Friday at the earliest.

File: test/java/build.gradle (hunk 11 above)
Comment (sahejsingh) [reply test/java/build.gradle]: ["src/main/java", "../../src/libs/java", "$tempDirectory"]

what is wrong with it? 
My understanding is 
java has src/{main,test}/.. directories...

File: test/java/src/test/java/TestJsonSerializer.java (hunk 29 above)
Comment (sahejsingh) [reply test/java/src/test/java/TestJsonSerializer.java]: the benefit is you don't need to add any new files. Have a look at TestPetShop.java.

File: .gitignore (hunk 24 above)
Comment (sahejsingh) [reply .gitignore]: "move to other relatives paths under .eggs"

not sure what you mean by that?

**Comment by juliaogris** [comment]
Ok, thanks for your patience and all your changes. There are some minor conflicts to be resolved (see above) which I think are causing the CI builds to fail.

Consider this approved from my end.

Let's now wait for @anzdaddy to do the real review on the actual guts of this PR in [`serializer.py`](https://github.com/anz-bank/sysl/pull/27/files#diff-c6d553ab49548f687ee5dd674a4af33b).
